directories:
  MP4: "/srv/samba/share/GoProFlights"
  IGC: "IGCData"
  PROCESSED_DATA: "ProcessedData"
  GPX: "ProcessedData/GPXData"
  TELEMETRY: "ProcessedData/TelemetryData"
  TRAJECTORY: "ProcessedData/TrajectoryData"
  ACTOR_DATA: "ProcessedData/ActorData"
  GEOJSON: "ProcessedData/GeoJson"
  SUBTITLES: "ProcessedData/Subtitles"
  PLOTS: "ProcessedData/Plots"
  UNREAL_ROOT: "Unreal/EPBC"
  SEQUENCE_DATA: "Unreal/EPBC/Saved/FlightComposer/SequenceData"
  OVERLAY: "ProcessedData/Overlay"
  FONT_PATH: "Fonts"
